apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-deployment
        image: ghcr.io/misteroryon/test_ci_cd/app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8090