apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      port: "12000"
      endpoint: /example
      method: POST
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-nodeport
spec:
  type: NodePort
  selector:
    eventsource-name: webhook
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
      nodePort: 32000