apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      endpoint: /example
      method: POST
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-nodeport
  namespace: argo-events
spec:
  type: NodePort
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
      nodePort: 32000