apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    type: NodePort
    ports:
      - port: 12000
        targetPort: 12000
        nodePort: 31107
  webhook:
    example:
      endpoint: /example
      method: POST