apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
rules:
- apiGroups: ["argoproj.io"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]