apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app-rollout
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: ghcr.io/misteroryon/test_ci_cd/app:latest
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 8090
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 5m }
      - setWeight: 40
      - pause: { duration: 5m }
      - setWeight: 60
      - pause: { duration: 5m }
      - setWeight: 80
      - pause: { duration: 5m }
