apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redeploy-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: go-app-deployment-event
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: rollout-trigger
        k8s:
          operation: update
          source:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              name: go-app-deployment
              spec:
                template:
                  metadata:
                    annotations:
                      argo.rollouts.io/restartedAt: "{{ now }}"