apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redeploy-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: go-app-deployment-event
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: k8s-deployment-trigger
        k8s:
          group: apps
          version: v1
          resource: deployments
          operation: update
          source:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: go-app-deployment
                namespace: default
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: go-app
                template:
                  metadata:
                    labels:
                      app: go-app
                  spec:
                    containers:
                      - name: go-app-deployment
                        image: ghcr.io/misteroryon/test_ci_cd/app:latest