apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redeploy-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: go-app-deployment-event
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: rollout-trigger
        k8s:
          operation: patch
          source:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: go-app-deployment
                namespace: default
              spec:
                template:
                  metadata:
                    annotations:
                      redeploy-timestamp: ""
          parameters:
            - src:
                dependencyName: go-app-deployment-event
                dataKey: body.timestamp
              dest: spec.template.metadata.annotations.redeploy-timestamp