apiVersion: v1
kind: Service
metadata:
  name: go-app-deployment
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30107 
    - port: 12000
      targetPort: 12000
      nodePort: 31234
---
apiVersion: v1
kind: Service
metadata:
  name: eventsource-service
  namespace: argo-events
spec:
  selector:
    app: teamcity-event
  type: NodePort
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
      nodePort: 31234
