apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rollout-trigger-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: docker-image-update
      eventSourceName: docker-registry
      eventSourceNamespace: argo-events
      eventName: example
  triggers:
    - template:
        name: rollout-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: rollouts
          operation: update
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Rollout
              metadata:
                name: go-app-rollout
                namespace: default
              spec:
                template:
                  spec:
                    containers:
                      - name: go-app
                        image: ghcr.io/misteroryon/test_ci_cd/app:latest
